#!/bin/bash

set -u
set -e

. "$plugin_dir/functions"

# Creates the base of the app
create_app_skel
init_vars
parse_databases

# Installs everything
install_libs "httpd php mysql-c"

# Write configuration
config_php
config_httpd

# Installs app and prepares start
install_app
write_control