#!/bin/bash

set -e
set -u

control_dir="$(dirname $0)"
. "$control_dir/config"

cat "$app_dir/.genapp/setup_status/plugin_"*

echo "Starting apache web server"
exec bash -c "httpd -k start -f $app_dir/conf/httpd.conf -D FOREGROUND"