#!/bin/bash 

set -e
set -u

control_dir="$(dirname $0)"
while read _var ; do export $_var ; done < "$control_dir/config"

echo "Stopping apache gracefully"
exec bash -c "httpd -k graceful-stop -f $app_dir/conf/httpd.conf -D FOREGROUND"